BrandSquare/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BrandSquare.Models;
using BrandSquare.Classes;

namespace BrandSquare.Controllers
{
    public class BrandController : Controller
    {
        private BrandSquareModel BrandSqaureX = new BrandSquareModel();

        public string changeDetails(string brandName, string Bio, string homeAddress)
        {
            try
            {
                var brandy = X.GetBrand<Brand>(Session, true);
                if (brandy != null)
                {
                    try
                    {
                        var brand = BrandSqaureX.Brands.Where(b => b.BrandID == brandy.BrandID).ToList()[0];
                        brand.BrandBio = Bio;
                        brand.BrandHomeAddress = homeAddress;

                        BrandSqaureX.SaveChanges();
                        Session.Add(X.FullBrandX, brand);

                    }
                    catch (Exception ex)
                    {
                        throw new Exception("Unable to save changes , Try again later!");
                    }

                    return "done";
                }

                throw new Exception("You are not logged in");
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        public string ChangePassword(string brandName, string Old, string New)
        {
            try
            {
                var brandy = X.GetBrand<Brand>(Session, true);
                if (brandy != null)
                {
                    if (brandy.BrandPassword == Old)
                    {
                        brandy.BrandPassword = New;
                        try
                        {

                            BrandSqaureX.Brands.Where(b => b.BrandID == brandy.BrandID).ToList()[0].BrandPassword = New;
                            BrandSqaureX.SaveChanges();
                            Session.Add(X.FullBrandX, brandy);
                        }
                        catch (Exception ex)
                        {
                            throw new Exception("Unable to save changes , Try again later!");
                        }

                        return "done";
                    }
                }

                throw new Exception("Incorrect current password");
            }
            catch (Exception ex)
            {
                return "Incorrect current password";
            }
        }

        public string IsLoggedInBrand(string brandName = "")
        {
            try
            {
                var brandy = X.GetBrand<Brand>(Session, true);
                if (brandy == null)
                {
                    //The person is not logged in for real
                    var brand = X.GetBrand<Object>(Session);

                    if (brand == null)
                    {
                        return "Error Not Logged in";
                    }
                    else
                    {
                        return JavaScriptX.convertString(new { brand, LoggedIN = false });
                    }
                }
                else
                {
                    var brand = X.GetBrand<Object>(Session);
                    return JavaScriptX.convertString(new { brand, LoggedIN = true });
                }
            }
            catch (Exception ex)
            {
                return "Error Not Logged in";
            }
        }

        public ActionResult edit(string brandName)
        {
            var brand = X.GetBrand<Brand>(Session, true);
            if (brand != null)
            {
                if (brand.BrandName == brandName)
                {
                    return View(brand);
                }
            }
            return RedirectToAction("Index");
        }

        public string FindBrand(string brandName)
        {
            try
            {
                var brand = BrandSqaureX.Brands.Where(b => b.BrandName.ToLower() == brandName.ToLower()).First();
                var answer = new
                {
                    ID = brand.BrandID,
                    Name = brand.BrandName,
                    Logo = brand.BrandLogo
                };

                Session.Add(X.brandX, new { Name = answer.Name, ID = answer.ID, Logo = answer.Logo });

                var cookie = new HttpCookie("BrandDetails");
                cookie.Values.Add(X.CookieBrandID, answer.ID.ToString());
                cookie.Values.Add(X.CookieBrandName, answer.Name);
                cookie.Values.Add(X.CookieBrandLogo, answer.Logo);

                cookie.Expires.AddDays(7);
                Response.Cookies.Set(cookie);

                return JavaScriptX.convertString(answer);

            }
            catch (Exception ex)
            {
                return "Error brand name does not exist";
            }
        }

        public string Login(string brandName, string password)
        {

            Brand brandX = null;
            try
            {
                brandX = BrandSqaureX.Brands.Where(b => b.BrandName == brandName && b.BrandPassword == password).First();
                Session.Add(X.brandX, new { Name = brandX.BrandName, ID = brandX.BrandID, Logo = brandX.BrandLogo });
                Session.Add(X.FullBrandX, brandX);

                return "Done";
            }
            catch (Exception ex)
            {
                return "Incorrect Log in details";
            }
        }

        public string LogOut()
        {
            Session[X.FullBrandX] = null;
            return "done";
        }

        public ActionResult b(string brandName)
        {
            Brand brand = null;
            try
            {
                brand = BrandSqaureX.Brands.Where(acc => acc.BrandName == brandName).First();
                var currentBrand = X.GetBrand<Brand>(Session, true);
                if (currentBrand != null)
                {
                    if (currentBrand.BrandID == brand.BrandID)
                    {
                        return View("b", brand);
                    }
                }
                throw new Exception();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult All_Brands(string brandName)
        {
            //We are going to all the brands
            return View("All_Brands");
        }

        //The is the profile of the brand
        public ActionResult Index(string brandName)
        {
            Brand brand = null;
            try
            {
                brand = BrandSqaureX.Brands.Where(acc => acc.BrandName == brandName).First();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("Brand_Index", brand);
        }

        public string UpdateStatus(string Message)
        {
            var brand = X.GetBrand<Brand>(Session, true);
            if (brand != null)
            {
                try
                {
                    BrandSqaureX.Status.Add(new Status() { BrandID = brand.BrandID, DateTimePosted = X.FormatDateTime(DateTime.Now), Status1 = Message });
                    BrandSqaureX.SaveChanges();
                }
                catch (Exception ex) {
                    return "Unable to save you status, Try again later";
                }
                return "done";
            }
            return "You are not logged in";
        }

        public ActionResult Events(string brandName)
        {
            Brand brand = null;
            try
            {
                brand = BrandSqaureX.Brands.Where(acc => acc.BrandName == brandName).First();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(brand);
        }

        /*
        public string LoadMorePendingPosts(int userID, int index, int maxPosts = 8)
        {

            if (maxPosts == 0)
            {
                return JavaScriptX.convertString("No more Posts");
            }
            List<Post> posts = new List<Post>();

            LaundromatX.PostHelpers.Where(h => h.HelperID == userID && h.HelperAccepted == "false").ToList().ForEach((e) =>
            {
                posts.Add(e.Post);
            });

            if ((maxPosts + index > posts.Count) && maxPosts > 0)
            {
                return LoadMorePendingPosts(userID, index, maxPosts - 1);
            }

            posts.Reverse();

            try
            {
                posts = posts.GetRange(index, maxPosts);
            }
            catch (Exception ex)
            {

                if ((maxPosts + index > posts.Count) && maxPosts > 0)
                {
                    return LoadMorePosts(userID, index, maxPosts - 1);
                }
            }

            List<string> card = new List<string>();

            foreach (var p in posts)
            {
                card.Add(X.ConvertPost(p, Session, Url));
            }

            return JavaScriptX.convertString(card.ToArray());

        }

        public string LoadMorePosts(int userID, int index, int maxPosts = 8)
        {

            if (maxPosts == 0)
            {
                return JavaScriptX.convertString("No more Posts");
            }

            List<Post> posts = LaundromatX.Posts.Where(p => p.UserID == userID && p.Status.Contains("Waiting for help")).ToList();

            if ((maxPosts + index > posts.Count) && maxPosts > 0)
            {
                return LoadMorePosts(userID, index, maxPosts - 1);
            }

            posts.Reverse();

            try
            {
                posts = posts.GetRange(index, maxPosts);
            }
            catch (Exception ex)
            {

BrandSquare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body @ViewBag.Title class="fixed-sn grey-skin">
    <div id="Xapp">
        @if (BrandSquare.Classes.X.GetBrand<BrandSquare.Models.Brand>(Session, true) == null)
        {
            <x-login :login-brandname="LoginBrandname" :login-brandlogo="LoginBrandlogo" :login-brand-name-found="LoginBrandNameFound"></x-login>
        }
        <nav class="navbar navbar-fixed-bottom navbar-light grey lighten-3 row">
            @if (BrandSquare.Classes.X.GetBrand<BrandSquare.Models.Brand>(Session, true) == null)
            {
                <div class="col-xs-2 col-md-3">
                    <a class="btn btn-floating transparent waves-circle waves-effect" role="button" data-toggle="modal" data-target="#modal-login">
                        <i class="fa fa-3x fa-user black-text"></i>
                    </a>
                </div>
            }
            else
            {
                var brand = BrandSquare.Classes.X.GetBrand<BrandSquare.Models.Brand>(Session, true);
                <div class="col-xs-2 col-md-3">
                    <a class="btn btn-floating transparent waves-circle waves-effect" data-toggle="popover">
                        <i>
                            <img style="width:100%;height:100%" class="img-fluid img-circle" src="@brand.BrandLogo" />
                        </i>
                    </a>
                    <a class="btn btn-floating transparent waves-circle waves-effect" href="@Url.Action("b","Brand",new { brandName = brand.BrandName})">
                        <i class="fa fa-plus black-text">

                        </i>
                    </a>
                </div>
            }
            <div class="col-xs-6 offset-xs-1 col-md-4 offset-md-1 waves-effect" role="button" onclick="window.location.href='@Url.Action("Index","Home")'">
                <img src="~/Content/images/logo/BrandSqaure_transparent.png" style="width:100%;height:68px" class="img-fluid text-xs-center flex-center" />
            </div>
            <div class="col-xs-2 col-md-3 pull-md-right">
                <a class="btn btn-floating waves-circle transparent waves-effect pull-md-right" href="@Url.Action("About","Home")">
                    <i class="fa fa-3x fa-info black-text"></i>
                </a>
            </div>
        </nav>
        <div class="container-fluid">
            @RenderBody()
            <hr />
            <footer id="FooterX">
                <p>&copy; @DateTime.Now.Year - BrandSquare</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>